version: "3"
services:
  db:
    platform: linux/amd64    # Mac m1 칩인 경우 platform을 명시해줍니다.
    image: mysql:8.3.0
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=Alswn1858!
      - TZ=Asia/Seoul
    volumes:
      - /Users/kimminju/mysql/temp:/opt/homebrew/var/mysql